#!/bin/zsh
#ZSH Autoload
autoload -Uz compinit promptinit
compinit
promptinit

eval "$(starship init zsh)"

# Load antidote
source ~/.antidote/antidote.zsh
# initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load

# all of our zsh files
typeset -U config_files
config_files=(~/.zsh/*.zsh)

# load the path files
for file in ${config_files}; do
  source "$file"
done

# load the zsh function files
for file in ~/.zsh/functions/*; do
  source "$file"
done

# load zsh completion files
autoload -U compinit && compinit

setopt inc_append_history share_history autocd autopushd pushdignoredups
setopt COMPLETE_ALIASES

zstyle ':completion::complete:*' gain-privileges 1

# History
SAVEHIST=100000
HISTFILE=~/.zsh_history

