command_timeout = 10000

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
show_milliseconds = false
disabled = false
format = " 🕙 $duration($style) "
style = "bold italic #87A752"

# Git status is slow for large repositories
[git_status]
disabled = true

[character]
error_symbol = "[✖](bold red) "

# Disable package versions
[nodejs]
disabled = true

[ruby]
disabled = true
