#!/usr/bin/env bash
#
set -euo pipefail

if ! chezmoi="$(command -v chezmoi)"; then
  # One-shot means this will remove chezmoi after installation
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --one-shot robert-crandall
fi
