#!/usr/bin/env bash
#
# This is run on every Codespaces startup. See install_mac for the Mac version.
set -euo pipefail

if ! chezmoi="$(command -v chezmoi)"; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply robert-crandall # TODO - remove
  # One-shot means this will remove chezmoi after installation
  # sh -c "$(curl -fsLS get.chezmoi.io)" -- init --one-shot robert-crandall
fi