#!/usr/bin/env bash
#
# This is run on every Codespaces startup. See install_mac for the Mac version.
set -euo pipefail

# Use bin versions of tools
sudo ln -s /workspaces/github/bin/rubocop /usr/local/bin/rubocop
sudo ln -s /workspaces/github/bin/srb /usr/local/bin/srb
sudo ln -s /workspaces/github/bin/solargraph /usr/local/bin/solargraph
sudo ln -s /workspaces/github/bin/safe-ruby /usr/local/bin/ruby

if ! chezmoi="$(command -v chezmoi)"; then
  # can use -- init --one-shot instead of --apply to auto remove chezmoi
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply robert-crandall 
fi
